- swype-client/src/App.tsx
- swype-client/src/main.tsx
- swype-client/src/styled.d.ts
- swype-client/src/theme.ts
- theme fontWeight 추가
- font 오류 수정
수정하여 적용되는 것 확인하였습니다.
> feat: theme fontWeight 추가, font 오류 수정

- swype-client/src/styled.d.ts
- swype-client/src/theme.ts
> fix: theme 구조 일부 수정

- swype-client/src/common/Button.tsx
- 버튼 구현 완료
사용 예시)
사용하실 때에는 Button props 잘 확인하셔서 theme.ts에 지정한 값 적용하시면 될 것 같습니다.
> feat: 공통 Button 구현 완료

- swype-client/src/common/Header.tsx
- 작업하실 때 header가 빠르게 필요하실 것 같아 초안으로 UI만 간단하게 짜서 올려드립니다.
- 추후 수정 및 보완 예정입니다.
> feat: Header 컴포넌트 UI 초안

- swype-client/src/App.tsx
- swype-client/src/common/GlobalStyle.ts
- swype-client/src/components/ItemCard.tsx
- swype-client/src/main.tsx
- swype-client/src/pages/StoreMain.tsx
- main.tsx 에서 글씨체 적용 안되는 문제 !important 추가  ( 작업 중 글씨체 적용 안됌 )
- 아이템 컴포넌트 UI 구현
> feat: 아이템 카드 컴포넌트 UI 구현

- swype-client/src/styled.d.ts
- swype-client/src/theme.ts
- feat: 폰트 size rem값 추가
- styled.d.ts 파일에 type 지정이 아닌 숫자값을 적어줬어서 일부 수정하였습니다.
- font 객체 추가하여 weight랑 size를 내부에 넣어줬습니다. 혹시나 fontWeight으로 사용하셨다면 theme.ts 확인하시고 수정해주시면 될 것 같아요!
> feat: 폰트 size rem값 추가, type 지정 코드 일부 수정

- swype-client/src/common/Button.tsx
공통 Button style 수정
- theme 수정되어 알맞게 style 수정하였습니다.
- letter-spacing rem값으로 수정하였습니다.
> fix: 공통 Button style 수정

- swype-client/src/common/Header.tsx
Header 컴포넌트 초안 완료해서 일단 기능 구현 전까지 사용하시면 될 것 같습니다.
> feat: Header 컴포넌트 초안 완료 #6

- swype-client/src/styled.d.ts
- swype-client/src/theme.ts
theme: textColor 수정 반영하였습니다.
- white 색상 추가
- colors.google 색상 변경
> fix: theme - textColor 수정 반영

- swype-client/src/App.tsx
- swype-client/src/components/ItemCard.tsx
- swype-client/src/pages/store/StoreDetail.tsx
- swype-client/src/pages/store/StoreMain.tsx
- 상점 페이지에서 아이템 상세 페이지 UI 작업 완료
> feat: 아이템 상세 페이지 UI 구현 #18

- swype-client/src/components/CharacterForm.tsx
- swype-client/src/pages/CharacterSelection.tsx
- swype-client/src/pages/SelectedCharacter.tsx
- png 파일 교체하여 수정하였습니다.
- 선택 페이지 택스트 추가 구현하였습니다.
> feat: 캐릭터 선택 페이지 텍스트 추가, 설명페이지 UI 변경 적용

- swype-client/src/App.tsx
- swype-client/src/components/ItemModal.tsx
- swype-client/src/components/QuizModal.tsx
- swype-client/src/pages/quiz/Quiz.tsx
> fix: 퀴즈페이지 배경화면 버그 수정

- swype-client/src/App.tsx
- swype-client/src/Router.tsx
- swype-client/src/main.tsx
- swype-client/src/pages/quiz/Quiz.tsx
> feat: 라우터 설정

- swype-client/package.json
- swype-client/src/Router.tsx
- swype-client/src/common/Header.tsx
- swype-client/src/pages/Movie.tsx
- swype-client/yarn.lock
- react-player 라이브러리 사용
- 헤더 props 받아와서 영상페이지일때 헤더 아이콘 색상 변경
- pull로 땡겨와서 yarn dev 하기전 패키지 설치 : pull → yarn install → yarn dev
> feat: 영상페이지 UI 구현 #45

- swype-client/src/pages/Movie.tsx
> feat: 영상 페이지 기능  구현 #50

- swype-client/src/components/common/Header.tsx
- swype-client/src/main.tsx
- swype-client/src/pages/Stage.tsx
- swype-client/src/theme.ts
글씨 크기 16px을 기준으로 잡고 %값으로 수정하였습니다.
> fix: header, 글씨 크기 변경 사항 적용

- swype-client/src/apis/trashImg.ts
- swype-client/src/apis/trashPoint.ts
- swype-client/src/apis/trashStatusCheck.ts
- swype-client/src/apis/userInfo.ts
- swype-client/src/components/LoginForm.tsx
- 포인트 적용 확인 완료
- isClean false -> true 변경 확인 완료
- 배경, 캐릭터 이미지, 캐릭터 이름, 레벨 구현 완료 (캐릭터 선택 페이지 구현 후 확인 필요)
> fix 오염된 페이지 에러 핸들링 추가 및 API 호출 함수 개선 #67

- swype-client/src/components/Modal/ItemModal.tsx
- swype-client/src/model/storeType.ts
- swype-client/src/pages/Charcter.tsx
- swype-client/src/pages/store/StoreDetail.tsx
> feat: 아이템 구매 모달 기능 구현 #80

- swype-client/package.json
- swype-client/src/components/Modal/InfoModal.tsx
- swype-client/src/model/characterType.ts
- swype-client/src/pages/Charcter.tsx
- swype-client/src/pages/SelectedCharacter.tsx
- swype-client/src/share/queries/useGetCharacter.ts
- swype-client/yarn.lock
- pull로 땡겨오시면 yarn install 먼저 해주세요. ( 리엑트 아이콘 패키치 설치함 )
-  ui부분 수정
- 라우팅 처리 아직 안했고 주소창에서 치셔야 해요
- 확인하시면 바로 머지 해주시면 됩니다.
> feat: 캐릭터 가입과정 기능 구현 #82

- swype-client/src/components/CharacterCard.tsx
- swype-client/src/components/FeatureButtons.tsx
- swype-client/src/components/Modal/InfoModal.tsx
- swype-client/src/pages/Charcter.tsx
- swype-client/src/pages/SelectedCharacter.tsx
- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/quiz/Quiz.tsx
- swype-client/src/pages/store/StoreDetail.tsx
- swype-client/src/share/utils/checkUser.ts
- 캐릭터 있는 유저가 주소창 /character , /selected 접속 시 못가게 처리
- UI 보완 작업
> feat : 권한없는 유저 주소창 이동시 불가처리 / UI 보완 작업

- swype-client/src/components/Modal/InfoModal.tsx
- swype-client/src/components/Modal/QuizModal.tsx
- swype-client/src/model/quizType.ts
- swype-client/src/pages/Charcter.tsx
- swype-client/src/pages/Loading.tsx
- swype-client/src/pages/SelectedCharacter.tsx
- swype-client/src/pages/quiz/Quiz.tsx
- swype-client/src/share/queries/useGetChance.ts
- swype-client/src/share/queries/useGetQuiz.ts
- 퀴즈 페이지 기능 구현
- 3번 다 풀었을때는 메인에서 막아줘야합니다
> feat: 퀴즈페이지 기능 구현 #89

- swype-client/src/components/FeatureButtons.tsx
- swype-client/src/components/ItemCard.tsx
- swype-client/src/model/storeType.ts
- swype-client/src/pages/store/StoreDetail.tsx
- swype-client/src/share/utils/Toast.ts
- 퀴즈 , 영상 남은 횟수 체크 로직 구현
- 상점페이지 타입지정 
- 기타 UI 수정
> feat: 퀴즈,영상 남은횟수 체크 로직 구현 & 상점페이지 타입지정 수정

- swype-client/src/components/CharacterCard.tsx
- swype-client/src/components/FeatureButtons.tsx
- swype-client/src/components/Modal/GiftModal.tsx
- swype-client/src/components/Modal/ItemModal.tsx
- swype-client/src/components/Modal/QuizModal.tsx
- swype-client/src/components/Point.tsx
- swype-client/src/components/QuizLife.tsx
- swype-client/src/main.tsx
- swype-client/src/model/quizType.ts
- swype-client/src/pages/Charcter.tsx
- swype-client/src/pages/SelectedCharacter.tsx
- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/quiz/Quiz.tsx
- swype-client/src/share/utils/checkUser.ts
- 퀴즈페이지 동일한 useQuery 키값쓰는거 수정
- build할때 안쓰는 import 에러뜨기때문에 안쓰는거 제거 했습니다
- 헤더 UI 수정
> fix: 퀴즈페이지 오류 수정 & UI 수정 및 안쓰는 import 제거

- swype-client/src/components/CharacterForm.tsx
- swype-client/src/components/LoginForm.tsx
- swype-client/src/components/Modal/GiftModal.tsx
- swype-client/src/components/Modal/ItemModal.tsx
- swype-client/src/components/Modal/QuizModal.tsx
- swype-client/src/components/Modal/TrashModal.tsx
- swype-client/src/components/Trash-related/TrashItem.tsx
- swype-client/src/components/common/Button.tsx
- swype-client/src/components/common/Header.tsx
- swype-client/src/model/trashType.ts
- swype-client/src/pages/Charcter.tsx
- swype-client/src/pages/Movie.tsx
- swype-client/src/pages/PollutedStage.tsx
- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/store/StoreDetail.tsx
- swype-client/src/share/recoil/dndAtoms.tsx
> fix: 페이지, 컴포넌트별 에러 처리

- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/store/StoreDetail.tsx
> fix: 상점 페이지 구매 불가 UI 수정

- swype-client/src/components/LoginForm.tsx
fix: LoginForm 버튼 넘침 UI 수정
`height : 100vh -> auto`
> fix: LoginForm 버튼 넘침 UI 수정

- swype-client/src/apis/quiz/getRemainContents.ts
- swype-client/src/apis/trash/getTrashStatusCheck.ts
- swype-client/src/apis/user/getCharacterMax.ts
- swype-client/src/apis/user/getUserInfo.ts
- swype-client/src/components/LoginForm.tsx
- swype-client/src/components/Modal/CompleteModal.tsx
- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/login/Loading.tsx
- swype-client/src/pages/login/Login.tsx
- 로그인 페이지 UI 수정 ( 잘될지 모르겠음 )
- 1번 오류 였던 토큰 undefined 오류 함수에서 token 생성하는 시점 변경
> fix: 로그인페이지 UI 수정 & 토큰 오류 해결

- swype-client/src/components/Modal/QuizModal.tsx
- swype-client/src/components/common/Point.tsx
퀴즈, 포인트 실시간 반영하였습니다. (퀴즈 차감, 포인트 사용시 포인트 감소)
> fix: 퀴즈, 포인트 실시간 반영 구현

- swype-client/src/components/Modal/CompleteModal.tsx
- swype-client/src/pages/Stage.tsx
> fix: 토큰 없을 때 스테이지 처리

- swype-client/src/components/Modal/GiftModal.tsx
> fix: 기프티콘 기능 구현

- swype-client/index.html
> thumbnail test

- swype-client/index.html
> chore: favicon, thumbnail test

- swype-client/src/components/Modal/GiftModal.tsx
> fix: 이메일 유효성 검사 정규표현식 사용

- swype-client/index.html
> fix : meta 태그 설정

- swype-client/src/pages/character/Charcter.tsx
> refactor: 캐릭터 미선택시 버튼 비활성화

- swype-client/src/components/character/CharacterCard.tsx
- swype-client/src/pages/character/Charcter.tsx
- 캐릭터 버튼 활성/비활성화 props 오류 수정
- 캐릭터 버튼 하단 border값 수정
> refactor: 캐릭터 버튼 활성/비활성화 props 오류 수정

- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/login/Loading.tsx
> fix: 로그인 라우팅 오류 수정

- swype-client/src/apis/item/getDetailItem.ts
- swype-client/src/apis/quiz/getQuiz.ts
- swype-client/src/apis/quiz/getRemainContents.ts
- swype-client/src/apis/user/getCharacter.ts
- swype-client/src/components/Modal/InfoModal.tsx
- swype-client/src/pages/Splash.tsx
- swype-client/src/pages/contents/Movie.tsx
- swype-client/src/pages/contents/Quiz.tsx
- PC에서만 호버 이벤트 적용
- 영상 사운드 수정
- console.log 에러 showToast로 에러 전부 처리
> fix: 호버 CSS 오류 수정 & 영상 사운드 수정 & 오류 처리

- swype-client/index.html
> chore: SWYG script 코드 추가

- swype-client/src/components/Modal/InfoModal.tsx
- swype-client/src/main.tsx
- swype-client/src/pages/login/Loading.tsx
> fix: 로그인 로직 변경 수정

- swype-client/src/main.tsx
ios font 적용 안 되는 이슈 있어서 2안으로 다른 font 적용하였습니다.
> refactor: ios font test

- swype-client/src/components/FeatureButtons.tsx
- swype-client/src/components/Modal/QuizModal.tsx
- swype-client/src/pages/contents/Quiz.tsx
- 모달창 애니메이션
- 메인에서 퀴즈 , 영상 커서 : 포인터
> fix: 퀴즈 모달창 애니메이션

- swype-client/src/pages/Stage.tsx
> fix: 이미지 겹침 문제 수정

- swype-client/index.html
- swype-client/src/App.tsx
- swype-client/src/Router.tsx
- swype-client/src/apis/item/buyItem.ts
- swype-client/src/apis/item/getDetailItem.ts
- swype-client/src/apis/quiz/getQuiz.ts
- swype-client/src/apis/user/getCharacter.ts
- swype-client/src/apis/user/getCheckUser.ts
- swype-client/src/components/FeatureButtons.tsx
- swype-client/src/components/Modal/CompleteModal.tsx
- swype-client/src/components/common/LoadingSpinner.tsx
- swype-client/src/main.tsx
- swype-client/src/pages/Stage.tsx
- swype-client/src/share/utils/Toast.ts
- React.Lazy & Suspense ( 15s → 8s )
- 무거운 함수 최적화  & 무거운 라이브러리 사용 고민 ( react-icons , Toast 함수 수정 )
- 로딩 스피너 추가 ( Suspense )
성능적으로 개선 시켰고 눈으로 보이는 UI는 크게 바뀐건 없습니다
> fix : 초기렌더링 속도 성능 개선 ( 15s -> 4s )

- swype-client/src/components/Modal/InfoModal.tsx
- swype-client/src/components/Modal/QuizModal.tsx
- swype-client/src/components/character/CharacterCard.tsx
- swype-client/src/pages/contents/Quiz.tsx
> fix: 토스트 알림 에러 수정

- swype-client/src/apis/user/getUserInfo.ts
> fix: 콘솔 제거 , 환경 변수 변경

- swype-client/src/components/Modal/GiftModal.tsx
- swype-client/src/components/common/Point.tsx
- swype-client/src/components/common/QuizLife.tsx
- swype-client/src/pages/contents/Movie.tsx
- swype-client/src/pages/login/Login.tsx
- swype-client/src/share/utils/Toast.ts
fix: env 파일 수정 및 font-weight theme 수정
> fix: env 파일 수정 및 font-weight theme 수정

- swype-client/package-lock.json
- swype-client/package.json
- swype-client/src/apis/item/buyItem.ts
- swype-client/src/key.ts
- swype-client/src/pages/Stage.tsx
- swype-client/src/pages/login/Loading.tsx
- swype-client/src/vite-env.d.ts
- swype-client/yarn.lock
- 쿠키에 저장되는 토큰 , url상에 노출되는 토큰 암호화
> fix : 로그인 토큰 값 암호화 하기
